Update to 1.21.4 + fog adjustment
Bactrosaurus/bactromod pull request #14
Opened 2024-12-06 21:37 UTC by Libreh

I updated the mod to 1.21.4 and made disabling the terrain fog not hide clouds (unlike before), let me know what you think!

2024-12-06 23:11 UTC, Bactrosaurus requested changes
Changes with no comments are ok.

2024-12-06 23:11 UTC, Bactrosaurus commented on build.gradle.kts
* Update Kotlin plugins jvm and serialization to version 2.1.0
* Update fabric-language-kotlin to 1.13.0+kotlin.2.1.0
* Update Mod-Menu to 13.0.0-beta.1 (adds Support for 1.21.4)

2024-12-06 23:11 UTC, Bactrosaurus commented on gradle/wrapper/gradle-wrapper.properties
* Update to Gradle 8.11.1 with gradle wrapper --gradle-version 8.11.1

2024-12-06 23:11 UTC, Bactrosaurus commented on src/main/java/de/daniel/bactromod/mixins/features/boatmap/MixinItemInHandRenderer.java
> +        float i = getLocalPlayer().getAttackAnim(1.0F);
Why? Look at target method call. We want to replicate behaviour of else branch which uses getAttackStrengthScale.

2024-12-06 23:11 UTC, Bactrosaurus commented on src/main/java/de/daniel/bactromod/mixins/features/windowborder/MixinWindow.java
> +    private void init(WindowEventHandler windowEventHandler, ScreenManager screenManager, DisplayData displayData, String string, String string2, CallbackInfo ci) {
Don't use generic names like string or string2, even if values are not used.

2024-12-06 23:11 UTC, Bactrosaurus commented on src/main/resources/fabric.mod.json
* Update fabric-language-kotlin to 1.13.0+kotlin.2.1.0

2024-12-07 09:10 UTC, Libreh commented
Thanks for the feedback!
How about now?

2024-12-07 21:38 UTC, merged

2024-12-07 21:39 UTC, Bactrosaurus commented
Thank you for fixing the minor issues!